export interface Country {
  code: string;
  name: string;
  dial: string;
  flag: string;
}

export const countries: Country[] = [
  { code: "US", name: "United States", dial: "+1", flag: "\u{1F1FA}\u{1F1F8}" },
  { code: "GB", name: "United Kingdom", dial: "+44", flag: "\u{1F1EC}\u{1F1E7}" },
  { code: "CA", name: "Canada", dial: "+1", flag: "\u{1F1E8}\u{1F1E6}" },
  { code: "AU", name: "Australia", dial: "+61", flag: "\u{1F1E6}\u{1F1FA}" },
  { code: "DE", name: "Germany", dial: "+49", flag: "\u{1F1E9}\u{1F1EA}" },
  { code: "FR", name: "France", dial: "+33", flag: "\u{1F1EB}\u{1F1F7}" },
  { code: "IN", name: "India", dial: "+91", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "IQ", name: "Iraq", dial: "+964", flag: "\u{1F1EE}\u{1F1F6}" },
  { code: "JP", name: "Japan", dial: "+81", flag: "\u{1F1EF}\u{1F1F5}" },
  { code: "CN", name: "China", dial: "+86", flag: "\u{1F1E8}\u{1F1F3}" },
  { code: "BR", name: "Brazil", dial: "+55", flag: "\u{1F1E7}\u{1F1F7}" },
  { code: "MX", name: "Mexico", dial: "+52", flag: "\u{1F1F2}\u{1F1FD}" },
  { code: "KR", name: "South Korea", dial: "+82", flag: "\u{1F1F0}\u{1F1F7}" },
  { code: "IT", name: "Italy", dial: "+39", flag: "\u{1F1EE}\u{1F1F9}" },
  { code: "ES", name: "Spain", dial: "+34", flag: "\u{1F1EA}\u{1F1F8}" },
  { code: "RU", name: "Russia", dial: "+7", flag: "\u{1F1F7}\u{1F1FA}" },
  { code: "SA", name: "Saudi Arabia", dial: "+966", flag: "\u{1F1F8}\u{1F1E6}" },
  { code: "AE", name: "United Arab Emirates", dial: "+971", flag: "\u{1F1E6}\u{1F1EA}" },
  { code: "EG", name: "Egypt", dial: "+20", flag: "\u{1F1EA}\u{1F1EC}" },
  { code: "NG", name: "Nigeria", dial: "+234", flag: "\u{1F1F3}\u{1F1EC}" },
  { code: "ZA", name: "South Africa", dial: "+27", flag: "\u{1F1FF}\u{1F1E6}" },
  { code: "PK", name: "Pakistan", dial: "+92", flag: "\u{1F1F5}\u{1F1F0}" },
  { code: "BD", name: "Bangladesh", dial: "+880", flag: "\u{1F1E7}\u{1F1E9}" },
  { code: "TR", name: "Turkey", dial: "+90", flag: "\u{1F1F9}\u{1F1F7}" },
  { code: "ID", name: "Indonesia", dial: "+62", flag: "\u{1F1EE}\u{1F1E9}" },
  { code: "PH", name: "Philippines", dial: "+63", flag: "\u{1F1F5}\u{1F1ED}" },
  { code: "VN", name: "Vietnam", dial: "+84", flag: "\u{1F1FB}\u{1F1F3}" },
  { code: "TH", name: "Thailand", dial: "+66", flag: "\u{1F1F9}\u{1F1ED}" },
  { code: "MY", name: "Malaysia", dial: "+60", flag: "\u{1F1F2}\u{1F1FE}" },
  { code: "SG", name: "Singapore", dial: "+65", flag: "\u{1F1F8}\u{1F1EC}" },
  { code: "NZ", name: "New Zealand", dial: "+64", flag: "\u{1F1F3}\u{1F1FF}" },
  { code: "SE", name: "Sweden", dial: "+46", flag: "\u{1F1F8}\u{1F1EA}" },
  { code: "NO", name: "Norway", dial: "+47", flag: "\u{1F1F3}\u{1F1F4}" },
  { code: "DK", name: "Denmark", dial: "+45", flag: "\u{1F1E9}\u{1F1F0}" },
  { code: "FI", name: "Finland", dial: "+358", flag: "\u{1F1EB}\u{1F1EE}" },
  { code: "NL", name: "Netherlands", dial: "+31", flag: "\u{1F1F3}\u{1F1F1}" },
  { code: "BE", name: "Belgium", dial: "+32", flag: "\u{1F1E7}\u{1F1EA}" },
  { code: "CH", name: "Switzerland", dial: "+41", flag: "\u{1F1E8}\u{1F1ED}" },
  { code: "AT", name: "Austria", dial: "+43", flag: "\u{1F1E6}\u{1F1F9}" },
  { code: "PL", name: "Poland", dial: "+48", flag: "\u{1F1F5}\u{1F1F1}" },
  { code: "PT", name: "Portugal", dial: "+351", flag: "\u{1F1F5}\u{1F1F9}" },
  { code: "GR", name: "Greece", dial: "+30", flag: "\u{1F1EC}\u{1F1F7}" },
  { code: "IE", name: "Ireland", dial: "+353", flag: "\u{1F1EE}\u{1F1EA}" },
  { code: "IL", name: "Israel", dial: "+972", flag: "\u{1F1EE}\u{1F1F1}" },
  { code: "JO", name: "Jordan", dial: "+962", flag: "\u{1F1EF}\u{1F1F4}" },
  { code: "LB", name: "Lebanon", dial: "+961", flag: "\u{1F1F1}\u{1F1E7}" },
  { code: "KW", name: "Kuwait", dial: "+965", flag: "\u{1F1F0}\u{1F1FC}" },
  { code: "QA", name: "Qatar", dial: "+974", flag: "\u{1F1F6}\u{1F1E6}" },
  { code: "BH", name: "Bahrain", dial: "+973", flag: "\u{1F1E7}\u{1F1ED}" },
  { code: "OM", name: "Oman", dial: "+968", flag: "\u{1F1F4}\u{1F1F2}" },
  { code: "AR", name: "Argentina", dial: "+54", flag: "\u{1F1E6}\u{1F1F7}" },
  { code: "CL", name: "Chile", dial: "+56", flag: "\u{1F1E8}\u{1F1F1}" },
  { code: "CO", name: "Colombia", dial: "+57", flag: "\u{1F1E8}\u{1F1F4}" },
  { code: "PE", name: "Peru", dial: "+51", flag: "\u{1F1F5}\u{1F1EA}" },
  { code: "KE", name: "Kenya", dial: "+254", flag: "\u{1F1F0}\u{1F1EA}" },
  { code: "GH", name: "Ghana", dial: "+233", flag: "\u{1F1EC}\u{1F1ED}" },
  { code: "MA", name: "Morocco", dial: "+212", flag: "\u{1F1F2}\u{1F1E6}" },
  { code: "TN", name: "Tunisia", dial: "+216", flag: "\u{1F1F9}\u{1F1F3}" },
  { code: "DZ", name: "Algeria", dial: "+213", flag: "\u{1F1E9}\u{1F1FF}" },
  { code: "LY", name: "Libya", dial: "+218", flag: "\u{1F1F1}\u{1F1FE}" },
  { code: "SD", name: "Sudan", dial: "+249", flag: "\u{1F1F8}\u{1F1E9}" },
  { code: "SY", name: "Syria", dial: "+963", flag: "\u{1F1F8}\u{1F1FE}" },
  { code: "YE", name: "Yemen", dial: "+967", flag: "\u{1F1FE}\u{1F1EA}" },
  { code: "PS", name: "Palestine", dial: "+970", flag: "\u{1F1F5}\u{1F1F8}" },
  { code: "UA", name: "Ukraine", dial: "+380", flag: "\u{1F1FA}\u{1F1E6}" },
  { code: "RO", name: "Romania", dial: "+40", flag: "\u{1F1F7}\u{1F1F4}" },
  { code: "HU", name: "Hungary", dial: "+36", flag: "\u{1F1ED}\u{1F1FA}" },
  { code: "CZ", name: "Czech Republic", dial: "+420", flag: "\u{1F1E8}\u{1F1FF}" },
  { code: "HR", name: "Croatia", dial: "+385", flag: "\u{1F1ED}\u{1F1F7}" },
  { code: "RS", name: "Serbia", dial: "+381", flag: "\u{1F1F7}\u{1F1F8}" },
  { code: "BG", name: "Bulgaria", dial: "+359", flag: "\u{1F1E7}\u{1F1EC}" },
  { code: "ET", name: "Ethiopia", dial: "+251", flag: "\u{1F1EA}\u{1F1F9}" },
  { code: "TZ", name: "Tanzania", dial: "+255", flag: "\u{1F1F9}\u{1F1FF}" },
  { code: "UG", name: "Uganda", dial: "+256", flag: "\u{1F1FA}\u{1F1EC}" },
  { code: "CM", name: "Cameroon", dial: "+237", flag: "\u{1F1E8}\u{1F1F2}" },
  { code: "SN", name: "Senegal", dial: "+221", flag: "\u{1F1F8}\u{1F1F3}" },
  { code: "CI", name: "Ivory Coast", dial: "+225", flag: "\u{1F1E8}\u{1F1EE}" },
  { code: "MM", name: "Myanmar", dial: "+95", flag: "\u{1F1F2}\u{1F1F2}" },
  { code: "NP", name: "Nepal", dial: "+977", flag: "\u{1F1F3}\u{1F1F5}" },
  { code: "LK", name: "Sri Lanka", dial: "+94", flag: "\u{1F1F1}\u{1F1F0}" },
  { code: "AF", name: "Afghanistan", dial: "+93", flag: "\u{1F1E6}\u{1F1EB}" },
  { code: "IR", name: "Iran", dial: "+98", flag: "\u{1F1EE}\u{1F1F7}" },
  { code: "HK", name: "Hong Kong", dial: "+852", flag: "\u{1F1ED}\u{1F1F0}" },
  { code: "TW", name: "Taiwan", dial: "+886", flag: "\u{1F1F9}\u{1F1FC}" },
  { code: "EC", name: "Ecuador", dial: "+593", flag: "\u{1F1EA}\u{1F1E8}" },
  { code: "VE", name: "Venezuela", dial: "+58", flag: "\u{1F1FB}\u{1F1EA}" },
  { code: "CU", name: "Cuba", dial: "+53", flag: "\u{1F1E8}\u{1F1FA}" },
  { code: "DO", name: "Dominican Republic", dial: "+1", flag: "\u{1F1E9}\u{1F1F4}" },
  { code: "GT", name: "Guatemala", dial: "+502", flag: "\u{1F1EC}\u{1F1F9}" },
  { code: "HN", name: "Honduras", dial: "+504", flag: "\u{1F1ED}\u{1F1F3}" },
  { code: "SV", name: "El Salvador", dial: "+503", flag: "\u{1F1F8}\u{1F1FB}" },
  { code: "CR", name: "Costa Rica", dial: "+506", flag: "\u{1F1E8}\u{1F1F7}" },
  { code: "PA", name: "Panama", dial: "+507", flag: "\u{1F1F5}\u{1F1E6}" },
  { code: "JM", name: "Jamaica", dial: "+1", flag: "\u{1F1EF}\u{1F1F2}" },
  { code: "TT", name: "Trinidad and Tobago", dial: "+1", flag: "\u{1F1F9}\u{1F1F9}" },
  { code: "SO", name: "Somalia", dial: "+252", flag: "\u{1F1F8}\u{1F1F4}" },
];

export function findCountryByDial(dial: string): Country | undefined {
  return countries.find((c) => c.dial === dial);
}

export function findCountryByCode(code: string): Country | undefined {
  return countries.find((c) => c.code === code);
}
